Repository multiverse-team-11/inventory-app, pull requests merged in 2024-06, with the labels that each got.

#27 Test initial get
  index.test.js
  package-lock.json
  package.json
Labels: tier 1

#35 Add testing for Add Item
  index.test.js
Labels: tier 2

#38 single page view
  public/react/Root.jsx
  public/react/components/App.jsx
  public/react/components/Footer.jsx
  public/react/components/Form.jsx
  public/react/components/Header.jsx
  public/react/components/Item.jsx
  public/react/components/ItemsList.jsx
  public/react/pages/Form.jsx
  public/react/pages/Item.jsx
  public/react/pages/ItemsList.jsx
  public/style.css
Labels: tier 1

#39 Add testing for Update and Delete Items
  index.test.js
  server/routes/items.js
Labels: tier 3, tier 4

#44 Test server validations
  index.test.js
Labels: tier 5

#48 Bugs - Tweak validation price, display price, integer to currency and form items need name or id
  index.test.js
  public/react/Root.jsx
  public/react/components/Form.jsx
  public/react/components/Item.jsx
  public/react/pages/Item.jsx
  public/react/pages/ItemsList.jsx
  server/models/index.js
  server/routes/items.js
Labels: bug

#64 Change responsiveness view
  public/style.css
Labels: tier 5

#68 added website link to markdown file
  HELLO.md
Labels: documentation
